### ISSUE TITLE
Is VERSION now required?

### ISSUE THREAD

**Issue by bradleygolden** [Betree/burnex#33]
After the latest bump, we're getting the following error after from `mix compile`:

```
** (File.Error) could not read file "VERSION": no such file or directory
```

I think the culprit line can be found here: https://github.com/Betree/burnex/blob/ebc62f3029409142d749c58cee8e1155baba4773/mix.exs#L7

Our project does following semantic versioning but we do not use the `VERSION` file as you do with this project. Would it be possible to exclude this file from being required in order to use this dependency?

**Comment by Betree** [comment]
@bradleygolden thank you for opening an issue, this change was only related to the internal release mechanism and shouldn't have impacted projects that depend on it. I'll make sure to push a fix for it today.

**Comment by Betree** [comment]
Fixed in https://hex.pm/packages/burnex/1.2.1
