### ISSUE TITLE
[feature] MX record DNS lookup (RFC)

### ISSUE THREAD

**Issue by peaceful-james** [Betree/burnex#49]
I think it would be nice to use `dns` lib (https://github.com/tungd/elixir-dns) or similar to do a `:mx` lookup and validate the mail server domains returned against the same list we check the actual email domain against.

Maybe it's kind of paranoid but it seems like it would make `burnex` even safer.

What do people think of this idea?

**Comment by peaceful-james** [comment]
I made a PR for this: https://github.com/Betree/burnex/pull/50

**Comment by Betree** [comment]
@peaceful-james Sorry for the late reply on this issue, the way you've implemented that in https://github.com/Betree/burnex/pull/50 (making it optional) seems reasonable to me.

**Comment by peaceful-james** [comment]
@Betree I made a PR, as promised: https://github.com/Betree/burnex/pull/52

Two tests are failing for me, on the master branch (JFYI).

**Comment by peaceful-james** [comment]
@Betree I made a PR, as promised: https://github.com/Betree/burnex/pull/52

Two tests are failing for me, on the master branch (JFYI).

**Comment by Betree** [comment]
> Two tests are failing for me, on the master branch (JFYI).

Thanks for the info, it seems the doctests were broken in https://github.com/Betree/burnex/pull/47. Opened https://github.com/Betree/burnex/pull/54 to fix them.

**Comment by Betree** [comment]
Implemented in https://github.com/Betree/burnex/pull/50l, refactored in https://github.com/Betree/burnex/pull/52
