### ISSUE TITLE
[feature] allow library users to specify providers

### ISSUE THREAD

**Issue by alexbenic** [Betree/burnex#77]
`Burnex` users *have* to use providers that come with the library, we can make this library more flexible by accepting optional `providers` argument for. This would allow library users to edit provider list or keep their own while reusing logic. 

This would be a *backwards* compatible change. Suggested API change:

```
  iex> providers = ["badomain.org"]
  iex> Burnex.is_burner?("test@badomain.org, providers: providers)
```
or more realistic:
```
  @good_domains ["com.ar", ...]
  @providers Burnex.providers() |> MapSet.delete(@good_domains)

  ...

  def is_burner?(email) do
     Burnex.is_burner?(email, providers: @providers)
  end
```

It's possible to do all of this in "userspace", but we pretty much have to re-implement lib.

**Comment by Betree** [comment]
Resolved by https://github.com/Betree/burnex/pull/78
